### PR TITLE
fix: react rules in typescript

### PR DESCRIPTION
**Pull request by dannytce**

### CODE REVIEW

**Review by robertrossmann — CHANGES_REQUESTED** [review]
Apologies for the gigantic delay. 🥺

As it stands, everyone who is interested in using the typescript ruleset suddenly gets a bunch of useless packages installed (all the react-related plugins and other deps). This is very... unacceptable. 😇 

I think, however, it might be possible to still salvage this approach to some extent. If we assume that people who use this particular configuration file (`@strv/eslint-config-typescript/react`) also use the `@strv/eslint-config-react` ruleset, we can simply `require()` it without listing it as a dependency. 💡 I would even agree to STFU the linter telling us to list that dep in our _package.json_ file, as long as there is a nice comment above it explaining why we do this. 💯

**Comment by dannytce** [comment]
@robertrossmann apologies from my side as well 😅 

Anyway - I applied your suggestion (removed the `@strv/eslint-config-react` from the dependency list) and added additional note in docs :)

**Comment by robertrossmann** [comment]
@dannytce Looks good, nice!

However, the _package-lock.json_ file should not be updated like this, I think what happened here is you `cd`ed into this package's directory and ran `npm install`. However, you should always install all deps from the project's root with `make`, as that will delegate to `lerna` to install everything necessary.

You will have to undo the package-lock's changes, clean everything up and do a fresh install to fix this. 😢

**Comment by dannytce** [comment]
@robertrossmann good catch, thank you :) I supposedly run everything as I should. Tho I still have an issue with formatting - looks like the previous `package-lock.json` was using tabs, my version is using spaces. But there is not other change to the file.

Is it good to go? Or what do you think? 🤔

**Comment by dannytce** [comment]
@robertrossmann ok nevermind, fixed :)

**Review by robertrossmann — APPROVED** [review]
w00t! 🚀

**Pull request merged**
