### PR TITLE
feat: create stylelint config for react native applications

### PR DESCRIPTION
**Pull request by developer239**

### CODE REVIEW

**Comment by developer239** [comment]
@robertrossmann Can you please check why is CI failing? 🙂

**Comment by robertrossmann** [comment]
Hey @developer239, thanks a bunch for this contribution! 🎉 

I think we should really consider merging this pull request into the existing codebase for `stylelint-config-styled-components` and rename that package to just `stylelint-config` (as described in #7), otherwise we'd end up with several packages for stylelint and honestly I'd like to avoid that. 😇 

Would you be up to that task? 🙏

The idea would be to have just one stylelint-related configuration package and within that package we would have different "entry points" for various stylelint configuration options, similar to what we have with our ESLint packages. It would probably require some changes to the `styled-components` codebase (mostly renaming stuff and updating _README_s).

Thanks in advance and don't worry if that's too much to ask right now. I'll find some other volunteer, hopefully, or I'll do it myself. 💪 💯

**Comment by developer239** [comment]
@robertrossmann So do you want to merge this request or do you want to close it and create another with totally different functionality? 🙂

**Comment by developer239** [comment]
@robertrossmann https://github.com/strvcom/code-quality-tools/pull/108

**Pull request closed without merging**
